// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJPiEEOhAV5m45S_2Oc6sMfra7eeJmHI',
    appId: '1:432176160698:web:909008f7b9904c51014783',
    messagingSenderId: '432176160698',
    projectId: 'fixero-9e0a9',
    authDomain: 'fixero-9e0a9.firebaseapp.com',
    databaseURL: 'https://fixero-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'fixero-9e0a9.firebasestorage.app',
    measurementId: 'G-X5T4VVLYSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCib0g6Kryicezu29z-UwOSGi22Qlg8swc',
    appId: '1:432176160698:android:570a9102ef8da835014783',
    messagingSenderId: '432176160698',
    projectId: 'fixero-9e0a9',
    databaseURL: 'https://fixero-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'fixero-9e0a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANtr91nWDAalDa0ieE-mXugKH_MYmCq6k',
    appId: '1:432176160698:ios:75cc58c3f978b46e014783',
    messagingSenderId: '432176160698',
    projectId: 'fixero-9e0a9',
    databaseURL: 'https://fixero-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'fixero-9e0a9.firebasestorage.app',
    androidClientId: '432176160698-6lqgfib403u0olfeihhe5dr6crb9s5rf.apps.googleusercontent.com',
    iosClientId: '432176160698-gnsfhej6kbj3ot8p0dse0tkrqip0irbu.apps.googleusercontent.com',
    iosBundleId: 'com.fixero.fixero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANtr91nWDAalDa0ieE-mXugKH_MYmCq6k',
    appId: '1:432176160698:ios:75cc58c3f978b46e014783',
    messagingSenderId: '432176160698',
    projectId: 'fixero-9e0a9',
    databaseURL: 'https://fixero-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'fixero-9e0a9.firebasestorage.app',
    androidClientId: '432176160698-6lqgfib403u0olfeihhe5dr6crb9s5rf.apps.googleusercontent.com',
    iosClientId: '432176160698-gnsfhej6kbj3ot8p0dse0tkrqip0irbu.apps.googleusercontent.com',
    iosBundleId: 'com.fixero.fixero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBJPiEEOhAV5m45S_2Oc6sMfra7eeJmHI',
    appId: '1:432176160698:web:cf5666bc50593cad014783',
    messagingSenderId: '432176160698',
    projectId: 'fixero-9e0a9',
    authDomain: 'fixero-9e0a9.firebaseapp.com',
    databaseURL: 'https://fixero-9e0a9-default-rtdb.firebaseio.com',
    storageBucket: 'fixero-9e0a9.firebasestorage.app',
    measurementId: 'G-JHDJZRSP7Z',
  );

}